language: java
jdk:
  - oraclejdk8
os:
  - linux
sudo: false
cache:
  directories:
    - .autoconf
    - $HOME/.m2
addons:
  apt:
    packages:
      - graphviz
script:
  - echo $SC_BUILD_DIR
  - cd "./schemacrawler-plugins-starter-parent"
  - mvn -Dcomplete clean package
 